name: deploy
on:
  push:
    branch:
      - main

jobs:
  cancel-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Yarn Install
        run: cd website && yarn
      - name: Build
        run: cd website && yarn run build
      - name: Export
        run: cd website && yarn run export
